name: sofia
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  google_sign_in: ^4.5.1
  shared_preferences: ^0.5.7+3
  google_fonts: ^1.1.0
  websafe_svg: ^1.1.0
  font_awesome_flutter: ^8.8.1
  flutter_tts: ^1.2.2
  speech_to_text: ^2.2.0
  showcaseview: ^0.1.5
  camera: ^0.5.8+2
  video_player: ^0.10.11+1
  flutter_auth0: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/model/
